### ISSUE TITLE
Unable to request token

### ISSUE THREAD

**Issue by thanhvg** [alphapapa/pocket-reader.el#52]
Hi, 

I'm a happy user of this package for years. Recently after installing this package in a new machine I am unable to authorize it with pocket service.  Here is the error I got. 

```
pocket-lib--request-token: pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error pocket-lib: Unable to get request token: (error Lisp nesting exceeds ‘max-lisp-eval-depth’))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

```

Only the authentication is not working for me. On my other machines where the package was authorized years ago it is working fine with the latest version from MELPA. Looks like there is a major change to  `plz` which may cause the problem or I didn't follow the instruction. Any insight or a confirmation/unconfirmation would be greatly appreciated.

Thanks

**Comment by alphapapa** [comment]
Hi,

Yes, please see https://github.com/alphapapa/pocket-lib.el/pull/7.  Sorry for the breakage.  In the meantime, you can install v0.3 of `pocket-reader` and v0.2 of of `pocket-lib`, which are known-good versions.

**Comment by alphapapa** [comment]
FYI, this is fixed on `pocket-lib`'s master branch.  I'll tag a new stable release if no more bugs are reported in it.  Please let me know if it works for you now.

**Comment by thanhvg** [comment]
Thanks for your fast response, I got another error. But please note that I didn't set up it properly:
- I did a quick eval buffer of the new pocket-lib on my current live emacs instance. 
- `pocket-reader`, got the url, opened it it browser. press authorize. 
- try `pocket-reader` again, got this error, I deducted the sensitive parts with `censored`

```
condition-case: pocket-lib--access-token: Unable to get access token: (plz-http-error "HTTP error" #s(plz-error nil #s(plz-response 2 403 ((content-type . "text/html; charset=UTF-8") (content-length . "13") (date . "Fri, 07 Jun 2024 14:16:08 GMT") (server . "Apache/2.4.52 (Debian)") (set-cookie . "PHPSESSID=censored; path=/; HttpOnly") (x-frame-options . "SAMEORIGIN") (x-error . "User rejected code.") (x-error-code . "158") (status . "403 Forbidden") (cache-control . "private") (x-source . "Pocket") (set-cookie . "AUTH_BEARER_default=censored; expires=Fri, 07-Jun-2024 15:16:08 GMT; Max-Age=3600; path=/; HttpOnly") (p3p . "policyref=\"/w3c/p3p.xml\", CP=\"ALL CURa ADMa DEVa OUR IND UNI COM NAV INT STA PRE\"") (x-cache . "Error from cloudfront") (via . "1.1 09701f8b2a1866d72a24a6230bb8aac8.cloudfront.net (CloudFront)") (x-amz-cf-pop . "YVR52-P2") (x-amz-cf-id . "censored")) "403 Forbidden") nil))
````

Again, it could be on me because I didn't reinstall pocket-reader. I will carry out a proper test later.

Thanks.

**Comment by thanhvg** [comment]
Confirm that pocket-reader get token is working fine after eval'ing  both the `pocket-lib` and `plz`.

Thank you very much!

**Comment by alphapapa** [comment]
Thank you for the confirmation.

**Comment by lentil32** [comment]
Issue remains 

> Thanks for your fast response, I got another error. But please note that I didn't set up it properly:
> 
> * I did a quick eval buffer of the new pocket-lib on my current live emacs instance.
> * `pocket-reader`, got the url, opened it it browser. press authorize.
> * try `pocket-reader` again, got this error, I deducted the sensitive parts with `censored`
> 
> ```
> condition-case: pocket-lib--access-token: Unable to get access token: (plz-http-error "HTTP error" #s(plz-error nil #s(plz-response 2 403 ((content-type . "text/html; charset=UTF-8") (content-length . "13") (date . "Fri, 07 Jun 2024 14:16:08 GMT") (server . "Apache/2.4.52 (Debian)") (set-cookie . "PHPSESSID=censored; path=/; HttpOnly") (x-frame-options . "SAMEORIGIN") (x-error . "User rejected code.") (x-error-code . "158") (status . "403 Forbidden") (cache-control . "private") (x-source . "Pocket") (set-cookie . "AUTH_BEARER_default=censored; expires=Fri, 07-Jun-2024 15:16:08 GMT; Max-Age=3600; path=/; HttpOnly") (p3p . "policyref=\"/w3c/p3p.xml\", CP=\"ALL CURa ADMa DEVa OUR IND UNI COM NAV INT STA PRE\"") (x-cache . "Error from cloudfront") (via . "1.1 09701f8b2a1866d72a24a6230bb8aac8.cloudfront.net (CloudFront)") (x-amz-cf-pop . "YVR52-P2") (x-amz-cf-id . "censored")) "403 Forbidden") nil))
> ```
> 
> Again, it could be on me because I didn't reinstall pocket-reader. I will carry out a proper test later.
> 
> Thanks.

Hi.

For me, even with `pocket-lib` v0.3-pre and `pocket-reader` v0.4-pre, above error occurs.
(also tried evaling latest `plz`, didn't work)

**Comment by alphapapa** [comment]
@lentil32 Please reproduce the problem in a clean Emacs configuration, e.g. using https://github.com/alphapapa/with-emacs.sh  If you can reproduce it, please file a new bug report with all the relevant information.

**Comment by alphapapa** [comment]
@lentil32 Nevermind, I found and fixed the problem in pocket-lib, see https://github.com/alphapapa/pocket-lib.el/commit/21f69179ad254ab64cb876115719e5d7d043f88d  Thanks for reporting.

**Comment by lentil32** [comment]
> @lentil32 Nevermind, I found and fixed the problem in pocket-lib, see [alphapapa/pocket-lib.el@21f6917](https://github.com/alphapapa/pocket-lib.el/commit/21f69179ad254ab64cb876115719e5d7d043f88d) Thanks for reporting.

Problem fixed on me either. Thanks
